<?php
/*
 * Generated configuration file
 * Generated by: phpMyAdmin 4.9.7 setup script
 * Date: Thu, 06 May 2021 12:31:59 +0000
 */

/* Servers configuration */
$i = 0;

/* Server: localhost [1] */
$i++;
$cfg['Servers'][$i]['only_db'] = '';
$cfg['Servers'][$i]['hide_db'] = '';

/* End of servers configuration */

$cfg['Console']['Mode'] = 'collapse';
$cfg['blowfish_secret'] = 'n>|lI7C*AyM;dZ/TTV<n1:rtK<KyFB7:';
$cfg['DefaultLang'] = 'en';
$cfg['ServerDefault'] = 1;
$cfg['UploadDir'] = '';
$cfg['SaveDir'] = '';
?>